#pragma once

#include <cstdint>

namespace cafey::storage {

/**
 * @brief Origin of a brewing event (spec §7.2 table `eventos_preparo`).
 */
enum class EventOrigin : uint8_t {
    APP = 0,
    AGENDAMENTO = 1,
    BOTAO = 2,
};

/**
 * @brief A single pending brewing event, queued locally until connectivity
 * allows publishing it to the cloud (spec §5.4, §5.5).
 *
 * `evento_id` (bootId:seq, per FW-08) is generated by a later component;
 * this struct only carries the fields the local queue needs to persist.
 */
struct Event {
    uint32_t timestamp_inicio = 0; // epoch seconds
    uint32_t timestamp_fim = 0;    // epoch seconds
    EventOrigin origem = EventOrigin::APP;
};

} // namespace cafey::storage
