org.gradle.jvmargs=-Xmx512m -XX:+UseSerialGC -XX:MaxMetaspaceSize=160m -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.workers.max=1
org.gradle.vfs.watch=false
kotlin.daemon.jvmargs=-Xmx512m -XX:+UseSerialGC -XX:MaxMetaspaceSize=160m

kotlin.code.style=official
kotlin.mpp.stability.nowarn=true

android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin/Wasm ainda é alvo experimental do Compose Multiplatform.
kotlin.wasm.experimental.compose=true
kotlin.incremental.wasm=true
